#	$NetBSD: Makefile.liveimage,v 1.2 2018/12/15 18:03:17 gson Exp $

.include <bsd.own.mk>

KERN_SET=		minix-kernel
PRIMARY_BOOT=		bootxx_minixfs3
SECONDARY_BOOT=		boot_monitor
#SECONDARY_BOOT_ARG=	# unnecessary
EFIBOOT+=		${WORKDIR}/usr/mdec/bootia32.efi

USE_MBR=		yes
USE_GPT=		no
USE_GPTMBR=		no

.include "${.CURDIR}/../../../common/bootimage/Makefile.liveimage"
