#	$NetBSD: Makefile,v 1.1.26.2 2020/08/17 10:30:22 martin Exp $

PROG=		bootx64.efi
NEWVERSWHAT=	"EFI Boot (x64)"
CPUFLAGS=	-march=x86-64
GNUEFIARCH=	x86_64
LIBKERN_ARCH=	x86_64
LIBGNUEFI_ARCH=	x86_64
KLINK_MACHINE=	amd64
OBJCOPY_FORMAT=	--subsystem efi-app	--target=pei-x86-64

EFIBOOT_ACPI=	yes
EFIBOOT_FDT=	yes
EFIBOOT_MULTIBOOT2=	yes

.PATH:		${.CURDIR}/../x86
EXTRA_SOURCES=	efibootx64.c
EXTRA_SOURCES+=	efibootx86.c bootinfo.c efimemory.c
EXTRA_SOURCES+=	startprog64.S
EXTRA_SOURCES+=	multiboot64.S

COPTS+=		-mno-red-zone
CPPFLAGS+=	-DEFI_FUNCTION_WRAPPER
CPPFLAGS+=	-DEFIBOOT_X86

CPPFLAGS+=	-DEFIBOOT_ALLOCATE_MAX_ADDRESS=0x100000000ULL
CFLAGS+=	-DACPI_64BIT_PHYSICAL_ADDRESS
CFLAGS+=	-DEFIBOOT_ALIGN=0x200000
CFLAGS+=	-DEFIBOOT_MODULE_MACHINE=\"amd64\"

CWARNFLAGS.clang+=	-Wno-unknown-warning-option

.include "${.CURDIR}/../Makefile.efiboot"

# MINIX cross-objcopy lacks PE/COFF support; override after bsd includes
.if defined(__MINIX)
OBJCOPY= objcopy
.endif

release: check_RELEASEDIR
	${HOST_INSTALL_FILE} -m ${BINMODE} ${PROG} \
		${RELEASEDIR}/${RELEASEMACHINEDIR}/installation/misc
		
